version: '3.7'

services:

  jupyter_server:
    image: ltpdigital/eda
    volumes:
      - .:/app
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_pass